name: chumsy_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  adaptive_theme: ^3.2.0
  fluttertoast: ^8.2.1
  image_picker: ^0.8.7+1
  flutter_progress_hud: ^2.0.2
  syncfusion_flutter_sliders: ^21.1.38
  animations: ^2.0.7
  card_swiper: ^2.0.4
  flutter_animated_dialog: ^2.0.1
  el_tooltip: ^1.0.8
  sliding_up_panel: ^2.0.0+1
  auto_size_text: ^3.0.0
  file_picker: ^5.2.9
  share_plus: ^6.3.2
  pull_down_button: ^0.8.2
  flutter_inset_box_shadow: ^1.0.8
  simple_shadow: ^0.3.1
  google_fonts:
  flutter_svg:

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/introduction_animation/
    - assets/logo/
    - assets/login/
    - assets/register/
    - assets/home/
    - assets/extras/
    - assets/extras/icons/
    - assets/svg/

  # example:
  fonts:
    - family: Proxima
      fonts:
        - asset: assets/fonts/Proxima/Proxima_Nova_Alt_Light.otf
        - asset: assets/fonts/Proxima/Proxima_Nova_Alt_Regular.otf
        - asset: assets/fonts/Proxima/Proxima_Nova_Alt_Regular.otf
          style: italic
        - asset: assets/fonts/Proxima/Proxima_Nova_Alt_Bold.otf
          weight: 500
