import 'package:chumsy/ui/community/tweet.dart';

List<Tweet> tweets = const [
  Tweet(
    avatar: 'assets/register/avatar.png',
    username: 'Flutter',
    name: 'FlutterDev',
    timeAgo: '5m',
    text: 'assets/register/avatar.png',
    photo: 'assets/tweet/demo1.png',
    comments: '243',
    send: '23K',
    cheer: '112K',
  ),
  Tweet(
    avatar: 'assets/register/avatar.png',
    username: 'Flutter en Español',
    name: 'EsFlutter',
    timeAgo: '12m',
    text: 'Comunidad Flutter de habla hispana!',
    photo: 'assets/tweet/demo1.png',
    comments: '46',
    send: '4K',
    cheer: '17K',
  ),
  Tweet(
    avatar: 'assets/register/avatar.png',
    username: 'Android Dev',
    name: 'AndroidDev',
    timeAgo: '20m',
    text: 'News and announcements for developers from the Android team.',
    photo: 'assets/tweet/demo1.png',
    comments: '305',
    send: '20K',
    cheer: '1M',
  ),
  Tweet(
    avatar: 'assets/register/avatar.png',
    username: 'Google Play',
    name: 'GooglePlay',
    timeAgo: '21m',
    text:
        'We’re exploring the world’s greatest stories through movies, TV, games, apps, books and so much more. Up for new adventures and discoveries? Let’s play.',
    photo: 'assets/tweet/demo1.png',
    comments: '1K',
    send: '70K',
    cheer: '2M',
  ),
  Tweet(
    avatar: 'assets/register/avatar.png',
    username: 'Google',
    name: 'Google',
    timeAgo: '26m',
    text: 'HeyGoogle',
    photo: 'assets/tweet/demo1.png',
    comments: '10K',
    send: '500K',
    cheer: '22M',
  ),
];
